anchor_version = "0.19.0"
solana_version = "1.8.11"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "tests/fixture-key.json"

[scripts]
test = "yarn mocha"

[[test.genesis]]
address = "CRATwLpu6YZEeiVq9ajjxs61wPQ9f29s1UoQR9siJCRs"
program = "./artifacts/programs/crate_token.so"

[[test.genesis]]
address = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"
program = "./artifacts/programs/stable_swap.so"

[[test.genesis]]
address = "ARoWLTBWoWrKMvxEiaE2EH9DrWyV7mLpKywGDWxBGeq9"
program = "./artifacts/programs/arrow_sunny.so"

[[test.genesis]]
address = "SPQR4kT3q2oUKEJes2L6NNSBCiPW9SfuhkuqC9bp6Sx"
program = "./artifacts/programs/sunny.so"

[[test.genesis]]
address = "QMNeHCGYnLVDn1icRAfQZpjPLBNkfGbSKRB83G5d8KB"
program = "./artifacts/programs/quarry_mine.so"

[[test.genesis]]
address = "QMWoBmAyJLAsA1Lh9ugMTw2gciTihncciphzdNzdZYV"
program = "./artifacts/programs/quarry_mint_wrapper.so"

[programs.mainnet]
brrr = "BRRRot6ig147TBU6EGp7TMesmQrwu729CbG6qu2ZUHWm"
bankman = "BANKhiCgEYd7QmcWwPLkqvTuuLN6qEwXDZgTe6HEbwv1"

[programs.devnet]
brrr = "BRRRot6ig147TBU6EGp7TMesmQrwu729CbG6qu2ZUHWm"
bankman = "BANKhiCgEYd7QmcWwPLkqvTuuLN6qEwXDZgTe6HEbwv1"

[programs.testnet]
brrr = "BRRRot6ig147TBU6EGp7TMesmQrwu729CbG6qu2ZUHWm"
bankman = "BANKhiCgEYd7QmcWwPLkqvTuuLN6qEwXDZgTe6HEbwv1"

[programs.localnet]
brrr = "BRRRot6ig147TBU6EGp7TMesmQrwu729CbG6qu2ZUHWm"
bankman = "BANKhiCgEYd7QmcWwPLkqvTuuLN6qEwXDZgTe6HEbwv1"
